/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Leksandr (https://sketchfab.com/leksandr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/support-drone-concept-1839a4af10684320bdbc53ee9fd67f07
Title: Support_Drone_concept
*/
import { Float, useGLTF } from "@react-three/drei";

const Drone = (props) => {
  const { nodes, materials } = useGLTF("/models/Fighter_drone-c.glb");
  return (
    <Float floatIntensity={5} floatingRange={0.5}>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.korpus_low_mask_low_0.geometry}
          material={materials.mask_low}
          position={[0, 0, 0]}
          rotation={[-1.5, 0, -0.75]}
          scale={0.5}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/Fighter_drone-c.glb");
export default Drone;
