/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ankledot (https://sketchfab.com/Ankledot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/headphones-skullcandy-crusher-wireless-4e902017e4624547b440da0a6658a689
Title: Headphones Skullcandy Crusher Wireless
*/

import { Float, useGLTF } from "@react-three/drei";

const Headphones = (props) => {
  const { nodes, materials } = useGLTF("/models/headphones.glb");

  // Create a reference to the target
  return (
    <Float floatIntensity={1} floatingRange={0.5}>
      <group {...props} dispose={null}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Skullcandy_Crusher_M_Skullcandy_Crusher_0.geometry}
          material={materials.M_Skullcandy_Crusher}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.1}
        />
      </group>
    </Float>
  );
};

useGLTF.preload("/models/headphones.glb");
export default Headphones;
