/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: TooManyDemons (https://sketchfab.com/toomanydemons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hologram-console-bfbbb481e98e4be38774b1d0204c192c
Title: Hologram Console
*/

import { useGLTF } from "@react-three/drei";

const Hologram = (props) => {
  const { nodes, materials } = useGLTF("/models/Holo.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.MAT_Monitors01}
        scale={1.489}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial_1.geometry}
        material={materials.MAT_Monitors02}
        scale={1.489}
      />
    </group>
  );
};

useGLTF.preload("/models/Holo.glb");
export default Hologram;
